[settings]

# for upload
# [repositories]
# [repositories.mirror]
# url = "https://pypi.doubanio.com/simple/"
# url = "https://mirrors.aliyun.com/pypi/simple/"
# url = "https://mirrors.ustc.edu.cn/pypi/web/simple"
# url = "https://pypi.tuna.tsinghua.edu.cn/simple/"

# for install
[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
# name = "tsinghua"
# url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
default = true

[virtualenvs]
create = true
in-project = true
